### ISSUE TITLE
A classe spring-boot-greendogdelivery-casadocodigo/src/main/java/com/boaglio/casadocodigo/greendogdelivery/carga/RepositoryTest.java com erro

### ISSUE THREAD

**Issue by marmundo** [boaglio/spring-boot-greendogdelivery-casadocodigo#1]
As linhas de systemout tipo
`System.out.println(">>> Pedido 1 - Fernando : "+ pedidoDoFernando);`
geram erro devido ao objeto pedidoDoFernando.

Solução:

1. Retira o objeto
2. Faz o output diretamente da propriedade

**Comment by boaglio** [comment]
em qual branch isso ocorre?

**Comment by marmundo** [comment]
master

**Comment by boaglio** [comment]
Você está usando o _branch_ incorreto, mude para o _branch_  **crud**
