### ISSUE TITLE
#02

### ISSUE THREAD

**Issue by phmiranda** [boaglio/spring-boot-greendogdelivery-casadocodigo#2]
Quando irá ser lançado a atualização do livro utilizando a versão 2.* do Spring Boot totalmente no formato restful sem engines de templates.

**Comment by boaglio** [comment]
Olá @phmiranda , no momento estou atualizando o livro de MongoDB, o próximo será o de Spring Boot... mas ainda terá um capítulo de templates, afinal muita gente usa .  Sentiu falta de alguma coisa ? Pode comentar !

**Comment by phmiranda** [comment]
@boaglio acho que seria interessante mostrar a autenticação de usuários, consumir uma API externa (ViaCEP) e salvar o retorno da API na base de dados, pretendo reler seu livro e posso elencar aqui.

**Comment by phmiranda** [comment]
Quando for reescrever o livro @boaglio ,seria interessante abordar o consumo de API's externa usando WebClient ou RestTemplate (mesmo que vá entrar em modo obsoleto)

**Comment by boaglio** [comment]
Sua sugestão será considerada na próxima edição.
